version: '3'
services:
  urlshortener:
    image: nporcel/url-shortener:latest
    ports:
    - "8080:8080"
    links:
    - redis
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
volumes:
  redisdata:
