version: '3'
services:
  haproxy:
    image: haproxy:alpine
    volumes:
        - $PWD/haproxy:/usr/local/etc/haproxy:ro
    links:
      - urlshortenera
      - urlshortenerb
      - urlshortenerc
    ports:
      - "8080:80"
  urlshortenera:
    image: nporcel/url-shortener:latest
    links:
      - redis
    ports:
      - "9090:8080"
  urlshortenerb:
    image: nporcel/url-shortener:latest
    links:
      - redis
  urlshortenerc:
    image: nporcel/url-shortener:latest
    links:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
volumes:
  redisdata:
